name: revive
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/android_alarm_manager
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  geolocator: ^8.0.1
  strings: ^0.2.2
  encrypt: ^5.0.1
  intro_slider: ^3.0.2
  shared_preferences: ^2.0.11
  http: ^0.13.4
  fluttertoast: ^8.0.8
  progress_dialog: ^1.2.0
  back_button_interceptor: ^5.0.2
  flutter_statusbarcolor: ^0.2.2
  carousel_pro: ^1.0.0
  carousel_slider: ^4.0.0
  percent_indicator: ^3.4.0
  mongo_dart: ^0.7.4
  datetime_picker_formfield: ^2.0.0
  share: ^2.0.4
  flutter_local_notifications: ^9.1.5
  koukicons: ^2.0.2
  firebase_messaging: ^11.2.4
  firebase_auth: ^3.3.4
  image_picker: ^0.8.4+4
  modal_progress_hud: ^0.1.3
  flutter_spinkit: ^5.1.0
  google_fonts: ^2.1.1
  url_launcher: ^6.0.17
  flutter_paginator: ^0.0.6
    
dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   flutter_statusbarcolor_ns: ^0.4.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/bg.png
    - assets/images/logo.png
    - assets/fonts/Pacifico-Regular.tff
    - assets/fonts/Ubuntu-Regular.tff
    - assets/images/blood_doodle.jpg
    - assets/images/image7.jpeg
    - assets/images/image5.jpg
    - assets/images/image6.jpeg
    - assets/images/profile.jpg
    - assets/fonts/Peterbuilt.ttf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.tff
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.tff
    - family: Peter
      fonts:
        - asset: assets/fonts/Peterbuilt.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
